Clean up queries for Arweave latest transactions
Bundlr-Network/validator-rust pull request #26
Opened 2022-04-06 16:56 UTC by mikonieminen

2022-04-06 19:55 UTC, bluekirby1111 commented
When running on this branch, I get the following error:
```
07:48:19.606 PM: ✖ Error occurred while getting txs from bundler address: 
 qxTjx4wDHbk-MjYQKeYJDmrFJ3Kek1fFss6ptfbxJDo. Error: MalformedQuery
 ```
We should pay attention on the `arweave.net` graphql api, apparently it has  a specific way to parse queries. The way it handled before was working.

2022-04-06 20:19 UTC, bluekirby1111 requested changes

2022-04-06 20:19 UTC, ghost commented on src/cron/arweave.rs
> +const TX_QUERY: &str = "query($owners: [String!], $first: Int) { transactions(owners: $owners, first: $first) { pageInfo { hasNextPage } edges { cursor node { id owner { address } signature recipient
Maybe move this query to a separate file

2022-07-27 11:15 UTC, closed without merging

2022-07-27 11:16 UTC, mikonieminen commented
This is not relevant anymore.